default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: nosql_demo_dev

test:
  <<: *default
  database: nosql_demo_test

production:
  <<: *default
  database: nosql_demo_prod
